### ISSUE TITLE
Github Deprecation for authentication via URL query parameters

### ISSUE THREAD

**Issue by ahmetb** [tugrulcan/license-alert#14]
Just received an email like this, I'm assuming this is from the personal access token I provided to this extension:

> ![image](https://user-images.githubusercontent.com/159209/73718425-510ae880-46d1-11ea-9c52-2b3093cedd8b.png)

It seems like unless it is fixed, I'll get a notification every 3 days.

**Comment by tugrulcan** [comment]
@ahmetb Thanks for the notification!
I will try my best to fix it before the second email arrives :+1:

**Comment by tugrulcan** [comment]
The authentication method is now updated to use headers instead of the URL query parameter. An update for the extension is currently pending review. 
![image](https://user-images.githubusercontent.com/12617804/73779694-66454d00-478d-11ea-8803-7e0a4b53316b.png)

As soon as it gets published, I will let you know!

Again, thanks a lot for the notification! 
Please let me know if you would like me to update or extend the functionality of this extension.

**Comment by tugrulcan** [comment]
_Update(06/02/2020): We are still waiting for the review for the extension._
_Update(07/02/2020): We are still waiting for the review for the extension._

**Comment by tugrulcan** [comment]
The new version of the extension has been released today. So I am closing this issue. 
@ahmetb Thanks for the notification! 
Please re-open this issue or create another one if you would like me to update or extend the functionality of this extension.

**Comment by ahmetb** [comment]
Thank you. 🙏
